### ISSUE TITLE
Make home page

### ISSUE THREAD

**Issue by jared-cain** [NCain24/restaurant-app#1]
Acceptance criteria:
- As a user, when I visit the homepage, I should be able to click a button that takes me to the search page
- As a user, I should see an input field for searching restaurants.

Developer Notes:
- Create structure for `/` route
- Create structure for `/search` 

Blocking:
- Waiting for Figma Designs

**Comment by NCain24** [comment]
Issue solved. PR https://github.com/NCain24/restaurant-app/pull/2
