### ISSUE TITLE
Add functionality for fetching restaurants

### ISSUE THREAD

**Issue by jared-cain** [NCain24/restaurant-app#3]
As an end user, when i enter text into search, i should see the results in list view beneath the search bar

Developer Notes:
- Should fetch an API for restaurants 
- Should show loading state when fetching results
- Should show cards for restaurants in results of search
- Should consider "debouncing"

**Comment by NCain24** [comment]
![Search Page](https://github.com/NCain24/restaurant-app/assets/88724898/8dbb9e3a-0fc6-453f-90ef-23bcb30e81b6)


Design of restaurant cards.

**Comment by NCain24** [comment]
![Restaurant Cards](https://github.com/NCain24/restaurant-app/assets/88724898/5af0396d-96f7-450f-87bd-55f961932175)

Updated design of restaurant cards.

**Comment by NCain24** [comment]
Closed with PR https://github.com/NCain24/restaurant-app/pull/7
