### ISSUE TITLE
Setup mock server endpoint for restaurant testing

### ISSUE THREAD

**Issue by jared-cain** [NCain24/restaurant-app#4]
As a developer, I should have an api that I can retrieve restaurant data from. 

Developer Notes:
- Look into mock server websites. E.g ( https://my-json-server.typicode.com )

Definition of Done:
- Can retrieve restaurant info via endpoint

**Comment by NCain24** [comment]
Completed PR https://github.com/NCain24/restaurant-app/pull/5
