### ISSUE TITLE
Add OAuth login flow

### ISSUE THREAD

**Issue by jared-cain** [NCain24/restaurant-app#8]
As a developer, in order to protect our endpoints, we would like to have our users be authorized.

Acceptance Criteria:
- Users can login with Github auth.

Developer Notes:
- Next auth seems to be a solid solution for this.

**Comment by NCain24** [comment]
Draft of PR https://github.com/NCain24/restaurant-app/pull/9

**Comment by jared-cain** [comment]
> Draft of PR #9

Your head is in a good place by linking the PR, but the link is to an "open" PR and not "draft". We probably dont need to link to PR's if they're in "draft" state (future reference)

**Comment by NCain24** [comment]
add next auth correctly https://github.com/NCain24/restaurant-app/pull/10

**Comment by NCain24** [comment]
Proper commit for adding next-auth and cleaning up the styling: https://github.com/NCain24/restaurant-app/commit/9cbb5de177c44d7f901f1db3dd469035532d8f6e

**Comment by NCain24** [comment]
Closed with PR https://github.com/NCain24/restaurant-app/pull/10
